<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4oPigYM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4oPigYM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4oPigYM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4oPigYM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4oPigYM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4oPigYM',
    'container.build_id' => '6ddd9c63',
    'container.build_time' => 1618794183,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4oPigYM');
