<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDT9xioF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDT9xioF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDT9xioF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDT9xioF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDT9xioF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DT9xioF',
    'container.build_id' => '045187b4',
    'container.build_time' => 1618702616,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDT9xioF');
