<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSsezAL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSsezAL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPSsezAL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPSsezAL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPSsezAL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PSsezAL',
    'container.build_id' => '983b3e5a',
    'container.build_time' => 1618795048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSsezAL');
